project_id = "gmnpjgelzsmcidwrwbcg"

[functions.analytics]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.recompute-entitlements]
verify_jwt = true
